const ACTIONS = {
  FETCHING_PRODUCTS_SUCCESS: 'FETCHING_PRODUCTS_SUCCESS',
  FETCHING_PRODUCTS_FAILURE: 'FETCHING_PRODUCTS_FAILURE',
  FETCHING_ORDERS_SUCCESS: 'FETCHING_ORDERS_SUCCESS',
  FETCHING_ORDERS_FAILURE: 'FETCHING_ORDERS_FAILURE',
  SET_CART_PRODUCTS: 'SET_CART_PRODUCTS',
  GET_CART_PRODUCTS: 'GET_CART_PRODUCTS',
  SET_REGISTER_SUCCES: 'SET_REGISTER_SUCCES',
  GET_REGISTER_SUCCES: 'GET_REGISTER_SUCCES',
  CLEAR_REGISTER_SUCCES: 'CLEAR_REGISTER_SUCCES',
};

export default ACTIONS;